### PR TITLE
fix(uiSelect) support data-multiple attribute

### LINKED ISSUE #1451: Using HTML5 data-* attributes breaks the multi-select and theme
I'm using a HTML5 validator, so I add data- in front of all of my attributes that are not standard HTML attributes. When I do this with the "multiple" attribute for ui-select, this causes uiSelectMatch directive to load an incorrect template.
I believe the error comes from here https://github.com/angular-ui/ui-select/blob/master/src/uiSelectMatchDirective.js#L12-L13 .

### PR DESCRIPTION
**Pull request by user378230**
uiSelectMatch was a special case where the non-normalised `multiple` attribute is checked, therefore using `data-multiple` resulted in the single select match template being loaded instead of the multiple-select-match template.

test is more involved than I would have liked but I couldn't see any other way to test it. 

Closes #1451

### CODE REVIEW

**Comment by wesleycho** [comment]
I'm not sure what your claimed support is, but here's a snippet in UI Bootstrap for what we check for: https://github.com/angular-ui/bootstrap/blob/master/src/tabs/tabs.js#L224-L234

File: src/uiSelectMatchDirective.js [hunk 1]
```diff
@@ -10,7 +10,10 @@ uis.directive('uiSelectMatch', ['uiSelectConfig', function(uiSelectConfig) {
 
       // Gets theme attribute from parent (ui-select)
       var theme = tElement.parent().attr('theme') || uiSelectConfig.theme;
-      var multi = tElement.parent().attr('multiple');
+
+      var multi = angular.isDefined(tElement.parent().attr('multiple')) ||
```
Comment (wesleycho) [inline src/uiSelectMatchDirective.js]: Probably worth caching `tElement.parent()` above and rewriting to remove duplicate calls to `.parent()`

**Comment by user378230** [comment]
Yeah I was being somewhat lazy, updated if you get a chance to review. .

**Comment by wesleycho** [comment]
LGTM
