### PR TITLE
fix(removeSelected) Unable to reselect item when removeselected set true

### LINKED ISSUE #1739: Unable to (re)select an item with remove-selected set to false
### Bug description:
```remove-selected=false``` seems to have a bug when you select an item and unselect the same item. You couldn't select again. Item was not disabled but click has not effect.

Steps to reproduce:

1. Go to http://plnkr.co/edit/o0JWRLkoMbMBkFi0crqh (same as documentation)
2. Go to the _Disabling instead of removing selected items_ section
3. Select _Amalie_ and remove _Amalie_ from the list.
4. Try to select _Amalie_ again. Not working.

### Link to minimally-working plunker that reproduces the issue:
http://plnkr.co/edit/o0JWRLkoMbMBkFi0crqh
### Version of Angular, UI-Select, and Bootstrap/Select2/Selectize CSS

Angular: 1.5.8

UI-Select: 0.18.1

Bootstrap/Select2/Selectize CSS (if applicable): Bootstrap

### PR DESCRIPTION
**Pull request by Jefiozie**
This will fix #1739

### CODE REVIEW

File: src/uiSelectMultipleDirective.js [hunk 1]
```diff
@@ -46,6 +46,7 @@ uis.directive('uiSelectMultiple', ['uiSelectMinErr','$timeout', function(uiSelec
         locals[$select.parserResult.itemName] = removedChoice;
 
         $select.selected.splice(index, 1);
+        $select.isDisabled(removedChoice);
```
Comment (user378230) [inline src/uiSelectMultipleDirective.js]: Is this needed? The result isn't actually used anywhere.

File: src/uiSelectController.js [hunk 2]
```diff
@@ -333,7 +333,7 @@ uis.controller('uiSelectCtrl',
     }
 
     if (!isDisabled && disabledItemIndex > -1) {
-      disabledItems.splice(disabledItemIndex, 0);
+      disabledItems.splice(disabledItemIndex, 1);
```
Comment (user378230) [inline src/uiSelectController.js]: Oops! Good spot! :blush:

File: src/uiSelectMultipleDirective.js (hunk 1 above)
Comment (Jefiozie) [inline src/uiSelectMultipleDirective.js]: You are correct.. missed that one :wink:
